version: '3.7'
services:

  front: 
    build:
      context: ./front
      dockerfile: Dockerfile
    image: demo-cicd-k8s-jenkins-front:latest
    
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: demo-cicd-k8s-jenkins-back:latest