version: '3.7'
services:
  web: 
    build:
      context: ./front
      dockerfile: Dockerfile
    image: demo-cicd-k8s-jenkins-front:latest
  app:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: demo-cicd-k8s-jenkins-front:latest