- hosts: all
  remote_user: root
  tasks:

    - name: Make .ssh
      file: 
        dest: /root/.ssh/ 
        state: directory

    - name: Check ssh key exist
      stat:
        path: /root/.ssh/id_rsa
      register: ssh_key

    - name: Generate ssh key if not exist
      shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
      when: not ssh_key.stat.exists

    - name: apt install
      apt:
        update_cache: yes
        name:
        - aptitude
        - docker-compose

    - name: Start/Enable docker
      systemd:
        name: docker
        state: started
        daemon_reload: no
        enabled: yes

    - name: Copy docker-compose.yml
      copy:
        src: ./docker-compose.yml
        dest: /root/docker-compose.yml

    - name: Copy Dockerfile
      copy:
        src: ./Dockerfile
        dest: /root/Dockerfile

    - name: Copy jenkins.sh
      copy:
        src: ./jenkins.sh
        dest: /root/jenkins.sh
        
    - name: Create secrets directory
      file:
        path: /root/secrets
        state: directory
        
    - name: Copy secrets dockerhost_password.txt
      copy:
        src: ./secrets/dockerhost_password.txt
        dest: /root/secrets/dockerhost_password.txt

    - name: Copy secrets dockerhub_password.txt
      copy:
        src: ./secrets/dockerhub_password.txt
        dest: /root/secrets/dockerhub_password.txt

    - name: Copy secrets dockerhub_secret.yml
      copy:
        src: ./secrets/dockerhub_secret.yml
        dest: /root/secrets/dockerhub_secret.yml

    - name: Copy secrets kubeconfig
      copy:
        src: ./secrets/kubeconfig
        dest: /root/secrets/kubeconfig
